Interface/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('getaway.urls'))
]

getaway/urls.py
from django.urls import path
from . import views

app_name = 'getaway'   # set name space

urlpatterns = [
    # http://localhost:8000
    path('', views.home, name='home'),
    path('<int:contentId>/', views.tour_detail, name='detail'),
    # http://localhost:8000/list
    path('list/', views.b_list, name='b_list'),
    # http://localhost:8000/list/create
    path('list/create/', views.b_create, name='b_create'),
    path('detail/<int:board_id>/', views.b_detail, name='b_detail'),
    path('modify/<int:board_id>/', views.b_modify, name='b_modify'),
    path('detail/remove/<int:board_id>/', views.b_remove, name='b_remove'),
    # 게시글 추천
    path('detail/<int:board_id>/like/', views.b_like, name='b_like'),
    # 회원가입/ 로그인/ 로그아웃
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    # 댓글......

]

getaway/models.py
from django.contrib.auth.models import User
from django.db import models


class Board(models.Model):
    b_title = models.CharField(max_length=100)  # 게시판 제목
    b_content = models.TextField(max_length=3000)  # 게시판 내용
    b_like = models.IntegerField(default=0)   # 게시판 좋아요 개수
    b_comment = models.IntegerField(default=0)  # 게시판 댓글 개수
    b_pubdate = models.DateTimeField(auto_now=True)  # 게시판 게시글 업로드 날짜
    b_user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, related_name='user_board')
    b_voter = models.ManyToManyField(User, related_name='voter_board', blank=True)  # 추천인 추가, Many-To-Many 중복 좋아요 방지

    def like_count(self):  # total user count
        return self.b_voter.count()

    def __str__(self):
        return self.b_title


class Comment(models.Model):
    c_content = models.TextField(max_length=1000)                   # 댓글 내용
    c_user = models.ForeignKey(User, on_delete=models.CASCADE)      # 댓글 쓴 유저
    c_like = models.IntegerField(default=0)                         # 댓글 좋아요
    c_pubdate = models.DateTimeField(auto_now=True)                 # 댓글 작성일
    c_board = models.ForeignKey(Board, on_delete=models.CASCADE)    # 이 댓글이 달린 게시글!

    def __str__(self):
        return self.c_content


class Tour(models.Model):
    t_name = models.CharField(max_length=50)
    t_like = models.IntegerField(default=0)
    t_dis = models.IntegerField(default=0)

    def __str__(self):
        return self.t_name


class TourComment(models.Model):
    tc_userID = models.CharField(max_length=20)
    tc_content = models.TextField(max_length=1000)
    tc_pubdate = models.DateTimeField(auto_now=True)
    tc_tour = models.ForeignKey(Tour, on_delete=models.CASCADE)

    def __str__(self):
        return self.tc_content


# 이름을 임시로 DefUser 로 바꿈. 장고 고유 User 랑 겹치길래...
# class DefUser(models.Model):
#     user_name = models.CharField(max_length=20)
#     user_password = models.CharField(max_length=20)
#     user_email = models.EmailField(max_length=40)
#     user_phone = models.IntegerField()
#     user_created = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return self.user_name

getaway/forms.py
from django import forms
from .models import *


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['b_title', 'b_content']                # 유저와 연동되어 써야하기 때문에 b_writer 를 제외 시켰음.
        # fields = ['b_title', 'b_writer', 'b_content']  # create 페이지에 보여줄 것들만 명시!


# Form 으로 코멘트 처리
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['c_user', 'c_content']
        # labels = {
        #     'content': '댓글내용',
        # }

getaway/views.py
from django.contrib.auth.hashers import check_password
from django.core.serializers import serialize
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from .forms import *
from django.core.paginator import Paginator
from django.db.models import Q  # for search function
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
import json


def b_list(request):
    """
    게시판 리스트 출력 함수
    """
    # 입력 파라미터
    user_id = request.session.get('user')
    print(user_id)
    page = request.GET.get('page', 1)  # 페이지
    kw = request.GET.get('kw', '')  # 검색어 for search function
    # 조회
    listing = Board.objects.all().order_by('-id')
    if kw:  # 이것도 for search function
        listing = listing.filter(
            Q(b_title__icontains=kw) |  # 제목검색
            Q(b_content__icontains=kw)  # | # 내용검색
        ).distinct()
    # 페이징 처리
    paginator = Paginator(listing, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    # 검색 기능 넣고 Page and kw are included
    context = {'listing': page_obj, 'page': page, 'kw': kw, 'user': user_id}
    return render(request, 'getaway/list.html', context)


def b_create(request):
    """
    게시글 작성
    """
    if request.method == 'POST':
        b_title = request.POST['b_title']
        b_content = request.POST['b_content']
        b_user = User.objects.get(pk=request.session.get('user'))
        new_post = Board(
            b_title=b_title,
            b_content=b_content,
            b_user=b_user,
        )
        new_post.save()
        return redirect('getaway:b_list')
    else:
        board_form = BoardForm()
        post = Board.objects.all()
        context = {
            'board_form': board_form,
            'post': post
        }
        return render(request, 'getaway/create.html', context)


@csrf_exempt
def b_detail(request, board_id):
    if request.method == 'POST':
        if request.POST.get('what') == 'write_comment':
            n_c_user = User.objects.get(pk=request.POST.get('writer'))
            n_c_content = request.POST.get('content')
            board = Board.objects.get(pk=request.POST['id'])
            board.b_comment += 1
            board.save()
            new_comment = Comment(
                c_user=n_c_user,
                c_content=n_c_content,
                c_board=board
            )
            new_comment.save()
            comment = Comment.objects.select_related('c_board').filter(c_board_id=request.POST.get('id')).order_by('-c_pubdate')
            writer = n_c_user.username
            comment_data = json.loads(serialize('json', comment))
            return JsonResponse({'comment': comment_data, 'writer': writer})
        elif request.POST.get('what') == 'comment_bring':
            comment = Comment.objects.select_related('c_board').filter(c_board_id=request.POST.get('id')).order_by('-c_pubdate')
            comment_data = json.loads(serialize('json', comment))
            username_data = {}
            for username in comment_data:
                username_data[username['fields']['c_user']] = User.objects.get(pk=username['fields']['c_user']).username
            return JsonResponse({'comment': comment_data, 'username': username_data})
        elif request.POST.get('what') == 'comment_delete':
            d_comment = Comment.objects.get(pk=request.POST.get('id'))
            d_comment.delete()
            board = Board.objects.get(pk=request.POST.get('board_id'))
            board.b_comment -= 1
            board.save()
            comment = Comment.objects.select_related('c_board').filter(c_board=request.POST.get('board_id')).order_by('-c_pubdate')
            comment_data = json.loads(serialize('json', comment))
            return JsonResponse({'comment': comment_data})

    if request.method == 'GET':
        user_id = request.session.get('user')
        post = get_object_or_404(Board, pk=board_id)
        comment_form = CommentForm()
        context = {
            'post': post,
            'comment_form': comment_form,
            'user': user_id
        }
        return render(request, 'getaway/detail.html', context)


def b_modify(request, board_id):
    post = get_object_or_404(Board, pk=board_id)
    if request.method == 'POST':
        post.b_title = request.POST['title']
        post.b_content = request.POST['content']
        post.b_user = User.objects.get(pk=request.session.get('user'))
        post.b_pubdate = request.POST['pubdate']
        post.save()
        return redirect('getaway:b_detail', board_id=post.id)
    else:
        context = {
            'post': post
        }
        return render(request, 'getaway/modify.html', context)


def b_remove(request, board_id):
    post = get_object_or_404(Board, pk=board_id)
    post.delete()
    return redirect('getaway:b_list')


def b_like(request, board_id):
    """
    좋아요 (추천) 기능 view 함수
    """
    user_id = request.session.get('user')
    post = get_object_or_404(Board, pk=board_id)
    if user_id is None:
        messages.error(request, '로그인한 유저만 좋아요를 누를 수 있습니다.')
    elif user_id == post.b_user.id:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    elif post.b_voter.filter(id=user_id).exists():
        post.b_voter.remove(user_id)
        messages.error(request, '좋아요가 취소 되었습니다.')
    else:
        post.b_voter.add(User.objects.get(pk=user_id))
    return redirect('getaway:b_detail', board_id)


# ----------------------------- 로긴
def signup(request):
    if request.method == 'POST':
        email = request.POST.get('email', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password1', None)
        re_password = request.POST.get('password2', None)
        if not (email and username and password and re_password):
            error = '모든 값을 입력해야 합니다.'
            return render(request, 'getaway/signup.html', {'error': error})
        elif password != re_password:
            error = '비밀번호가 일치하지 않습니다.'
            return render(request, 'getaway/signup.html', {'error': error})
        else:
            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password1'],
                email=request.POST['email'],
                )
            user.save()
            return render(request, 'getaway/signupcomplete.html')

    if request.method == 'GET':
        return render(request, 'getaway/signup.html')


def login(request):
    if request.method == 'GET':
        return render(request, 'getaway/login.html')
    elif request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        if not (username and password):
            error = '모든 값을 입력해야 합니다.'
        else:
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                error = '아이디가 존재하지 않습니다.'
            else:
                if check_password(password, user.password):
                    request.session['user'] = user.id
                    return redirect('/')  # 메인페이지
                else:
                    error = '비밀번호가 틀렸습니다.'
        return render(request, 'getaway/login.html', {'error': error})


def logout(request):
    if request.session.get('user'):
        del (request.session['user'])
    return redirect('getaway:b_list')


def home(request):
    user_id = request.session.get('user')
    if user_id:
        user = User.objects.get(pk=user_id)
        return render(request, 'getaway/mainpage.html', {'user_id': {user}})
    return render(request, 'getaway/mainpage.html')


@csrf_exempt
def tour_detail(request, contentId):
    if request.method == 'POST':
        try:
            Tour.objects.get(t_name=contentId)
        except Tour.DoesNotExist:
            tour = Tour.objects.create(t_name=contentId)
            if request.POST.get('what') == 'like':
                tour.t_like += 1
                tour.save()
            if request.POST.get('what') == 'dis':
                tour.t_dis += 1
                tour.save()
        else:
            tour = Tour.objects.get(t_name=contentId)
            if request.POST.get('what') == 'like':
                tour.t_like += 1
                tour.save()
            if request.POST.get('what') == 'dis':
                tour.t_dis += 1
                tour.save()
        return JsonResponse({'like': tour.t_like, 'dis': tour.t_dis})

    if request.method == 'GET':
        try:
            User.objects.get(pk=request.session.get('user'))
        except User.DoesNotExist:
            user = 'None'
        else:
            user = User.objects.get(pk=request.session.get('user'))
            print(user)

        try:
            tour = Tour.objects.get(t_name=contentId)
        except Tour.DoesNotExist:
            like = 0
            dis = 0
        else:
            like = tour.t_like
            dis = tour.t_dis
        return render(request, 'getaway/tourboard.html', {'contentId': contentId, 'user': user, 'like': like, 'dis': dis})


# --------------------------------------- comment 뷰 함수

def c_create(request, board_id):
    filled_form = CommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.board = get_object_or_404(Board, pk=board_id)
        finished_form.save()
    return redirect('getaway:b_detail', board_id)

getaway/templates/getaway/detail.html
{% load bootstrap4 %}
<!DOCTYPE HTML>
<!--
	Editorial by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>GETAWAY</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="../../static/assets/css/main.css" />
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
        <div id="wrapper">

            <!-- Main -->
            <div id="main">
                <div class="inner">

                    <!-- Header -->
                    <header id="header">
                        <a href="{% url 'getaway:home' %}" class="logo" id="{{ user }}"><strong>GETAWAY</strong> BUDDY</a>
                         <ul class="icons">
                            <div class="logout_div">
                                <ul class="underline-hover">
                                    {% if user != None %}
                                    <li class="logout_text"><a href="{% url 'getaway:logout' %}"><span>로그아웃</span></a></li>
                                    {% else %}
                                    <li class="logout_text"><a href="{% url 'getaway:login' %}"><span>로그인</span></a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </ul>
                    </header>
                    <br>
                <div>
                    <!-- 본인 게시글 좋아요 클릭 시, 사용자오류 표시 -->
                    {% if messages %}
                        <div class="alert alert-danger my-3" role="alert">
                            {% for message in messages %}
                                <blockquote>{{ message.message }}</blockquote>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div>
<!-- 게시글 제목, 목록으로 버튼 =------------------------------------------------------------------------------------------>
                        <button type="button"
                                class="button"
                                id="list_btn"
                                style="font-family: SansSerif; float: right;"
                                data-uri="{% url 'getaway:b_list' %}"> 목록으로 </button>

                    <h1 style="font-family: SansSerif;">{{ post.b_title }}</h1>
                </div>
                    <!-- Banner -->
                    <div class="content">
<!-- 게시글 내용 -------------------------------------------------------------------------------------------------------->
                        <div class="box">
                            <p class="card-text"></p>
                            <p class="card-text"
                               name="{{ post.id }}">글 번호 : <span id="board_id">{{ post.id }}</span><br>
                                                    작성자 : <span id="t_name">{{ post.b_user }}</span><br>
                                                    작성일 : {{ post.b_pubdate | date:"Y년 m월 d일 h:m" }}</p>
                            <hr>
                            <h3 style="font-family: SansSerif">{{ post.b_content }}</h3>
<!------------------------- 좋아요/수정/삭제 버튼 -------------------------------->
                            <div class="col-1">
                                <a href="{% url 'getaway:b_like' post.id %}"
                                   data-uri="{% url 'getaway:b_detail' post.id  %}">
                                    <button type="button"
                                            class="recommend primary"
                                            style="font-family: SansSerif">좋아요 {{post.b_voter.count}}</button>
                                </a>
                                <div style="float: right">
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        {% if user == post.b_user.id %}

                                            <button id="modify_btn"
                                                        type="button"
                                                        class="mod button"
                                                        data-uri="{% url 'getaway:b_modify' post.id %}"
                                                        style="font-family: SansSerif"> 수정 </button>

                                            <button type="button"
                                                    class="delete primary"
                                                    style="font-family: SansSerif"
                                                    data-uri="{% url 'getaway:b_remove' post.id  %}">삭제</button>

                                        {% endif %}
                                    </form>
                                </div>
                            </div>
                        </div>

<!--------------------------------- 코멘트를 한 번 넣어보자 ------------------------------------------------------>
                        <div class="container">
                            <h3 style="font-family: SansSerif" id="comment_count">댓글 {{ post.b_comment }}</h3>
<!------------------------------ 답변 등록 : form action link 달아야 함-->

                                <input type="hidden" value="{{ post.id }}" id="c_board">
                                <div class="row gtr-uniform">
                                    <div class="col-6 l" >
                                        <input type="text" id="c_content">
                                    </div>
                                    <div class="col-6 col-12-xsmall">
                                         <button type="submit" style="font-family: SansSerif" id="comment_btn">등록</button>
                                    </div>
                                </div>
                                <br>
                                <div id="c_list">
                                </div>
<!------------------------------ 등록된 답변 ------------------------------------->

                        </div>
                        <br><br><br>
                    </div>
                </div>
            </div>

<!-- Sidebar ---------------------------------------------------------------------------------------------------------->
            <div id="sidebar">
                <div class="inner">
                    <!-- Menu -->
                    <br><br><br>
                    <nav id="menu">
                        <header class="major">
                            <h2>Menu</h2>
                        </header>
                        <ul>
                            <li><a href="{% url 'getaway:home' %}" style="font-family: SansSerif">메인페이지</a></li>
                            <li><a href="{% url 'getaway:b_list' %}" style="font-family: SansSerif">자유게시판</a></li>
                        </ul>
                    </nav>
                    <!-- Section -->
                    <section>
                        <header class="major">
                            <h2>Who made this?</h2>
                        </header>
                        <article>
                            <a href="#" class="image">
                                <img src="../../static/images/park.png" style="width: 70%; height: 70%">
                            </a>
                            <p>github : Lewis911</p>
                        </article>
                        <article>
                            <a href="#" class="image">
                                <img src="../../static/images/ban.png" style="width: 70%; height: 70%">
                            </a>
                            <p>github : Rphabet</p>
                        </article>
                        <article>
                            <a href="#" class="image">
                                <img src="../../static/images/lee.png" style="width: 70%; height: 70%">
                            </a>
                            <p>github : 01stone</p>
                        </article>
                        <article>
                            <a href="#" class="image">
                                <img src="../../static/images/lim.png" style="width: 70%; height: 70%">
                            </a>
                            <p>github : Winmini</p>
                        </article>
                    </section>
                </div>
            </div>
        </div>

		<!-- Scripts -->
        <script src="../../static/assets/js/jquery.min.js"></script>
        <script src="../../static/assets/js/browser.min.js"></script>
        <script src="../../static/assets/js/breakpoints.min.js"></script>
        <script src="../../static/assets/js/util.js"></script>
        <script src="../../static/assets/js/main.js"></script>
        <script src="../../static/assets/js/buttons.js"></script>
        <script src="../../static/assets/js/comment_ajax.js"></script>

	</body>
</html>

getaway/templates/getaway/login.html
<!DOCTYPE HTML>
<!--
	Editorial by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Login</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="../../static/assets/css/main.css" />
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
        <div id="wrapper">

        <!-- Main -->
            <div id="main">
                <div class="inner">
                    <!-- Header -->
                    <header id="header">
                        <a href="{% url 'getaway:home' %}" class="logo"><strong>GETAWAY</strong> BUDDY</a>
                    </header>

                    <!-- Form -->
                    <br><br>
                    <div style="width: 50%; margin: 0 auto;">
                        <br>
                        <h1>Login</h1>

                        <form method="POST" action="{% url 'getaway:login' %}">
                            {% csrf_token %}
                            <!-- ID % PASSWORD 입력 -->
                            <input type="text" name="username" placeholder="ID" />
                            <br>
                            <input type="password" name="password" placeholder="Password" />
                            <br>
                            {% if error %}
                                <strong style="color: red"> {{ error }} </strong>
                            {% endif %}
                            <!-- LOGIN 버튼 -->
                            <ul class="actions" style="float: right;">
                                <li><input type="submit" value="Login" class="primary" /></li>
                                <li><input type="reset" value="Cancel" /></li> <!-- Main url? detail page? -->
                            </ul>
                            <br><br>
                        </form>
                        <!-- 회원가입 링크 -->
                        <a href="{% url 'getaway:signup' %}">아직 회원가입을 안했다면?</a>
                    </div>
                </div>


            </div>



        <!-- Sidebar -->
            <div id="sidebar">
                <div class="inner">
                    <!-- Menu -->
                    <br><br><br>
                    <nav id="menu">
                        <header class="major">
                            <h2>Menu</h2>
                        </header>
                        <ul>
                            <li><a href="{% url 'getaway:home' %}" style="font-family: SansSerif">메인페이지</a></li>
                            <li><a href="{% url 'getaway:b_list' %}" style="font-family: SansSerif">자유게시판</a></li>
                        </ul>
                    </nav>
                    <!-- Section -->
                    <section>
                        <header class="major">
                            <h2>Who made this?</h2>
                        </header>
                        <article>
                            <a href="#" class="image">
                                <img src="../../static/images/park.png" style="width: 70%; height: 70%">
                            </a>
                            <p>github : Lewis911</p>
                        </article>
                        <article>
                            <a href="#" class="image">
                                <img src="../../static/images/ban.png" style="width: 70%; height: 70%">
                            </a>
                            <p>github : Rphabet</p>
                        </article>
                        <article>
                            <a href="#" class="image">
                                <img src="../../static/images/lee.png" style="width: 70%; height: 70%">
                            </a>
                            <p>github : 01stone</p>
                        </article>
                        <article>
                            <a href="#" class="image">
                                <img src="../../static/images/lim.png" style="width: 70%; height: 70%">
                            </a>
                            <p>github : Winmini</p>
                        </article>
                    </section>
                </div>
            </div>
        </div>

		<!-- Scripts -->
			<script src="../../static/assets/js/jquery.min.js"></script>
			<script src="../../static/assets/js/browser.min.js"></script>
			<script src="../../static/assets/js/breakpoints.min.js"></script>
			<script src="../../static/assets/js/util.js"></script>
			<script src="../../static/assets/js/main.js"></script>
	</body>
</html>

getaway/templates/getaway/signup.html
<!DOCTYPE HTML>
<!--
	Editorial by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Sign-up</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="../../static/assets/css/main.css" />
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
        <div id="wrapper">

        <!-- Main -->
            <div id="main">
                <div class="inner">
                    <!-- Header -->
                    <header id="header">
                        <a href="{% url 'getaway:home' %}" class="logo"><strong>GETAWAY</strong> BUDDY</a>
                    </header>

                    <!-- Form -->
                    <br><br>
                    <div style="width: 50%; margin: 0 auto;">
                        <br>
                        <h1>Sign-up</h1>

                        <form method="post" action="{% url 'getaway:signup' %}">
                            {% csrf_token %}
                            <div class="col-6 col-12-xsmall" >
                                 <!-- 회원정보 입력 -->
                                <input type="email" name="email" placeholder="E-mail" />
                                <br>
                                <input type="text" name="username" id="demo-email" value="" placeholder="ID" />
                                <br>
                                <input type="password" name="password1" placeholder="Password" />
                                <br>
                                <input type="password" name="password2" placeholder="Confirm Password" />
                                <br>
                                <input type="text" name="digit" placeholder="Phone number" />
                                <br>
                                 <!-- 데커뤠이션 -->
                                <div class="col-6 col-12-small">
                                    <input type="checkbox" id="demo-ad" name="demo-ad">
                                    <label for="demo-ad">(선택) 광고성 메일 수신 동의</label>
                                </div>
<<<<<<< HEAD
                                {% if error %}
=======
                               {% if error %}
>>>>>>> 32b82f89c313b00551f1b11b519eaa9396d68cf7
                                    <strong style="color: red"> {{ error }} </strong>
                                {% endif %}
                                <!-- SIGNUP 버튼 -->
                                <ul class="actions" style="float: right;">
                                    <li>
                                        <input type="submit"
                                               style="font-family: SansSerif"
                                               class="button"
                                               value="회원가입"/>
                                    </li>
                                    <li>
                                            <button type="button"
                                                    class="go_home primary"
                                                    style="font-family: SansSerif">취소</button>
                                    </li>
                                </ul>
                                {% if error %}
                                {{ error }}
                                {% endif %}
                                <br><br>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

		<!-- Scripts -->
			<script src="../../static/assets/js/jquery.min.js"></script>
			<script src="../../static/assets/js/browser.min.js"></script>
			<script src="../../static/assets/js/breakpoints.min.js"></script>
			<script src="../../static/assets/js/util.js"></script>
			<script src="../../static/assets/js/main.js"></script>
            <script src="../../static/assets/js/buttons.js"></script>
	</body>
</html>